//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by CMS Entity ID Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Runtime.CMS
{
    public static class CMSConstants
    {
        public static class Test
        {
            public const string TestEntity = "Test/TestEntity";
        }
        public const string CMSEntityPrefab = "CMSEntityPrefab";
        public const string TestEcs = "Game.Runtime.CMS.TestEcs";
    }
}
