//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by CMS Entity ID Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Runtime.CMS
{
    public static class CMSPrefabs
    {
        public static class Audio
        {
            public static class SFX
            {
                public const string SFXClick = "CMS/Audio/SFX/SFXClick";
                public const string SFXImpact = "CMS/Audio/SFX/SFXImpact";
                public const string SFXKill = "CMS/Audio/SFX/SFXKill";
                public const string SFXTyping = "CMS/Audio/SFX/SFXTyping";
            }
            public const string Ambient = "CMS/Audio/Ambient";
        }
        public static class Services
        {
            public const string SayText = "CMS/Services/SayText";
            public const string UI = "CMS/Services/UI";
        }
    }
}
