//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by CMS Entity ID Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Runtime.CMS
{
    public static class CMSPrefabs
    {
        public static class Audio
        {
            public static class SFX
            {
                public const string SFXClick = "CMS/Audio/SFX/SFXClick";
                public const string SFXImpact = "CMS/Audio/SFX/SFXImpact";
                public const string SFXKill = "CMS/Audio/SFX/SFXKill";
                public const string SFXTyping = "CMS/Audio/SFX/SFXTyping";
            }
            public const string Ambient = "CMS/Audio/Ambient";
        }
        public static class Gameplay
        {
            public const string Character = "CMS/Gameplay/Character";
            public const string Customer = "CMS/Gameplay/Customer";
            public const string CustomersQueue = "CMS/Gameplay/CustomersQueue";
            public const string DinnerBehaviour = "CMS/Gameplay/DinnerBehaviour";
            public const string DishesLibrary = "CMS/Gameplay/DishesLibrary";
            public const string EmptyPlate = "CMS/Gameplay/EmptyPlate";
            public const string GameSettings = "CMS/Gameplay/GameSettings";
            public const string HUD = "CMS/Gameplay/HUD";
            public const string Kitchen = "CMS/Gameplay/Kitchen";
            public const string Tables = "CMS/Gameplay/Tables";
            public const string Trash = "CMS/Gameplay/Trash";
        }
        public static class Services
        {
            public const string UIService = "CMS/Services/UIService";
        }
    }
}
